sources:
  - name: overlayv2
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/proxy/46086/overlay-subgraph-arbitrum/v2.1.12
    transforms:
      - autoPagination:
          validateSchema: true
          limitOfRecords: 1000
